### PR TITLE
Refine dnsmasq conf-dir option

### LINKED ISSUE #162: dnsmasq: conf-dir option without trailing slash
Please remove the trailing slash in `/etc/dnsmasq.d/`
https://github.com/vimagick/dockerfiles/blob/950019082912998cff4a82556d5b8c11c175e5cb/dnsmasq/Dockerfile#L11

is visible at least in log output
`dnsmasq: unsupported option (check that dnsmasq was compiled with DHCP/TFTP/DNSSEC/DBus support) at line 2 of /etc/dnsmasq.d//dnssec.conf`

The example in [dnsmasq man](http://www.thekelleys.org.uk/dnsmasq/docs/dnsmasq-man.html) is `dir=/path/to/dir,*.conf`

### PR DESCRIPTION
**Pull request by bjmi**
Resolve #162

### CODE REVIEW

**Comment by bjmi** [comment]
@vimagick - please have a brief look at this PR.

**Comment by vimagick** [comment]
Thanks :+1:

**Comment by bjmi** [comment]
It looks like this merge commit isn't in vimagick:master. Please have look again.

**Comment by vimagick** [comment]
Some went wrong, so I reverted it. I'll fix it.
Thanks.

**Comment by bjmi** [comment]
Should this also go into arm dockerfile?

**Comment by vimagick** [comment]
Sure. I'm building the arm image. I'll push it to docker hub later.

**Pull request merged**
